name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/cache@v2
        if: ${{ env.CI_SKIP == 'false' }}
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/cache@v2
        if: ${{ env.CI_SKIP == 'false' }}
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}
      - name: Test
        run: yarn test


